
import React, { useState, useRef, useEffect } from 'react';
import { 
  Upload, FileText, ScanLine, Trash2, CheckCircle, AlertCircle, Loader2, 
  FileImage, Info, LayoutTemplate, PenTool, BookOpen, Send, 
  Check, Clock, Eye, X, RefreshCw, Link, FileSignature, History, Copy, ClipboardCheck, Wifi, ExternalLink, Download, FileCheck, ShieldCheck
} from 'lucide-react';
import { DocumentItem, Agreement, InvoiceTemplate, AuditEvent } from '../types';
import { GeminiService } from '../services/geminiService';

type Tab = 'uploads' | 'templates' | 'agreements' | 'msa';

const MOCK_TEMPLATES: InvoiceTemplate[] = [
  { id: 'Professional GST Standard', name: 'Professional GST Standard', thumbnailColor: 'bg-slate-200', tags: ['Professional', 'GST Compliant'] },
  { id: 'Creative Digital', name: 'Creative Digital', thumbnailColor: 'bg-indigo-100', tags: ['Modern', 'Freelancer'] },
  { id: 'Corporate Blue', name: 'Corporate Blue', thumbnailColor: 'bg-blue-100', tags: ['Corporate', 'Clean'] },
  { id: 'Minimalist Mono', name: 'Minimalist Mono', thumbnailColor: 'bg-gray-100', tags: ['Simple', 'B&W'] },
];

const INITIAL_AGREEMENTS: Agreement[] = [
  { 
    id: 'a1', 
    customerName: 'TechFlow India Pvt Ltd', 
    recipientEmail: 'accounts@techflow.in',
    type: 'MSA', 
    sentDate: '2024-05-10', 
    status: 'Signed', 
    lastActivity: 'Signed on 12 May',
    uniqueLink: 'https://grx10.app/sign/tf-msa-882',
    signedDocUrl: 'mock_signed_msa.pdf',
    auditTrail: [
       { id: 'e1', timestamp: '2024-05-10 10:00 AM', action: 'Created', details: 'Agreement generated by System' },
       { id: 'e2', timestamp: '2024-05-10 10:05 AM', action: 'Sent', details: 'Email sent to accounts@techflow.in' },
       { id: 'e3', timestamp: '2024-05-12 02:15 PM', action: 'Viewed', details: 'Link accessed from IP 103.22.1.4' },
       { id: 'e4', timestamp: '2024-05-12 02:30 PM', action: 'Signed', details: 'Digitally signed by R. Sharma' }
    ]
  },
  { 
    id: 'a2', 
    customerName: 'Reddy Enterprises', 
    recipientEmail: 'contact@reddyent.com',
    type: 'Service Contract', 
    sentDate: '2024-05-14', 
    status: 'Viewed', 
    lastActivity: 'Viewed 2 hours ago',
    uniqueLink: 'https://grx10.app/sign/re-sc-991',
    auditTrail: [
       { id: 'e1', timestamp: '2024-05-14 09:00 AM', action: 'Created', details: 'Agreement generated by System' },
       { id: 'e2', timestamp: '2024-05-14 09:01 AM', action: 'Sent', details: 'Email sent to contact@reddyent.com' },
       { id: 'e3', timestamp: '2024-05-14 11:45 AM', action: 'Viewed', details: 'Link accessed from IP 49.12.123.88' }
    ]
  },
  { 
    id: 'a3', 
    customerName: 'Global Exports Ltd', 
    recipientEmail: 'procurement@globalexports.com',
    type: 'NDA', 
    sentDate: '2024-05-15', 
    status: 'Sent', 
    lastActivity: 'Sent yesterday',
    uniqueLink: 'https://grx10.app/sign/ge-nda-104',
    auditTrail: [
       { id: 'e1', timestamp: '2024-05-15 04:00 PM', action: 'Created', details: 'Agreement generated by System' },
       { id: 'e2', timestamp: '2024-05-15 04:02 PM', action: 'Sent', details: 'Email sent to procurement@globalexports.com' }
    ]
  },
];

interface DocumentsProps {
  onUseTemplate?: (templateId: string) => void;
}

const Documents: React.FC<DocumentsProps> = ({ onUseTemplate }) => {
  const [activeTab, setActiveTab] = useState<Tab>('uploads');
  
  // --- OCR Logic ---
  const [documents, setDocuments] = useState<DocumentItem[]>([]);
  const [dragActive, setDragActive] = useState(false);
  const geminiRef = useRef<GeminiService | null>(null);

  // --- Agreements Logic ---
  const [agreements, setAgreements] = useState<Agreement[]>(INITIAL_AGREEMENTS);
  const [isSendModalOpen, setIsSendModalOpen] = useState(false);
  const [sendForm, setSendForm] = useState({ customerName: '', email: '', type: 'MSA' });
  const [isSending, setIsSending] = useState(false);
  
  // --- Signing Room Logic ---
  const [signingAgreement, setSigningAgreement] = useState<Agreement | null>(null);
  const [isSigning, setIsSigning] = useState(false); // Loading state for signing action
  
  // --- Audit Modal Logic ---
  const [viewAuditId, setViewAuditId] = useState<string | null>(null);
  const [copiedLinkId, setCopiedLinkId] = useState<string | null>(null);

  useEffect(() => {
    if (!geminiRef.current) {
      geminiRef.current = new GeminiService();
    }
  }, []);

  // --- Automatic Status Simulation (Real-time effect) ---
  useEffect(() => {
    const interval = setInterval(() => {
      setAgreements(prevAgreements => {
        const candidates = prevAgreements.filter(a => a.status === 'Sent' || a.status === 'Viewed');
        
        if (candidates.length === 0) return prevAgreements;

        // 30% chance to update a random record in this tick
        if (Math.random() > 0.7) {
            const candidate = candidates[Math.floor(Math.random() * candidates.length)];
            
            // Probability: Sent -> Viewed (High), Viewed -> Signed (Low), Sent -> Expired (Very Low)
            const rand = Math.random();
            const now = new Date();
            const timestamp = now.toLocaleString('en-IN', { hour: '2-digit', minute: '2-digit', day: 'numeric', month: 'short' });

            if (candidate.status === 'Sent' && rand > 0.8) {
               // Expire check (simulated)
               if (rand > 0.95) {
                 return prevAgreements.map(a => a.id === candidate.id ? { 
                     ...a, status: 'Expired', lastActivity: 'Link Expired', 
                     auditTrail: [...a.auditTrail, { id: Math.random().toString(), timestamp, action: 'Expired', details: 'Validity period ended' }] 
                 } : a);
               }
               // Sent -> Viewed
               return prevAgreements.map(a => a.id === candidate.id ? { 
                   ...a, status: 'Viewed', lastActivity: 'Viewed just now (Live)', 
                   auditTrail: [...a.auditTrail, { id: Math.random().toString(), timestamp, action: 'Viewed', details: 'Document opened by recipient via link' }] 
               } : a);
            } 
            
            // Viewed -> Signed (Handled mostly by manual simulation, but kept low prob here)
            if (candidate.status === 'Viewed' && rand > 0.9) {
                 return prevAgreements.map(a => a.id === candidate.id ? { 
                   ...a, status: 'Signed', lastActivity: 'Signed just now (Live)', signedDocUrl: 'auto_signed.pdf',
                   auditTrail: [...a.auditTrail, { id: Math.random().toString(), timestamp, action: 'Signed', details: `Digitally signed by ${a.customerName}` }] 
               } : a);
            }
        }
        return prevAgreements;
      });
    }, 5000); 

    return () => clearInterval(interval);
  }, []);

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault(); e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") setDragActive(true);
    else if (e.type === "dragleave") setDragActive(false);
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault(); e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) await handleFiles(Array.from(e.dataTransfer.files));
  };

  const handleFileInput = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) await handleFiles(Array.from(e.target.files));
  };

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve((reader.result as string).split(',')[1]);
      reader.onerror = error => reject(error);
    });
  };

  const handleFiles = async (files: File[]) => {
    const newDocs: DocumentItem[] = await Promise.all(files.map(async (file) => {
      const base64 = await fileToBase64(file);
      return {
        id: Math.random().toString(36).substring(2, 9),
        name: file.name,
        size: file.size,
        type: file.type,
        uploadDate: new Date().toISOString().split('T')[0],
        base64: base64,
        ocrStatus: 'idle'
      };
    }));
    setDocuments(prev => [...newDocs, ...prev]);
  };

  const runOCR = async (docId: string) => {
    const doc = documents.find(d => d.id === docId);
    if (!doc || !doc.base64) return;
    setDocuments(prev => prev.map(d => d.id === docId ? { ...d, ocrStatus: 'processing' } : d));
    try {
      const extractedData = await geminiRef.current!.parseDocument(doc.base64, doc.type);
      setDocuments(prev => prev.map(d => d.id === docId ? { ...d, ocrStatus: 'completed', extractedData: extractedData } : d));
    } catch (error) {
      console.error("OCR error", error);
      setDocuments(prev => prev.map(d => d.id === docId ? { ...d, ocrStatus: 'failed' } : d));
    }
  };

  const formatBytes = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const formatCurrency = (val?: number) => {
    if (val === undefined || val === null) return '-';
    return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(val);
  };

  // --- Agreement Handlers ---

  const handleSendAgreement = () => {
    if (!sendForm.customerName || !sendForm.email) return;
    
    setIsSending(true);
    setTimeout(() => {
      const now = new Date();
      const timestamp = now.toLocaleString('en-IN', { hour: '2-digit', minute: '2-digit', day: 'numeric', month: 'short' });
      const uniqueToken = Math.random().toString(36).substring(2, 10);
      
      const newAgreement: Agreement = {
        id: Math.random().toString(36).substring(2, 9),
        customerName: sendForm.customerName,
        recipientEmail: sendForm.email,
        type: sendForm.type as any,
        sentDate: new Date().toISOString().split('T')[0],
        status: 'Sent',
        lastActivity: 'Sent via email just now',
        uniqueLink: `https://grx10.app/sign/${sendForm.type.toLowerCase()}-${uniqueToken}`,
        auditTrail: [
          { id: 'e1', timestamp: timestamp, action: 'Created', details: 'Agreement generated by System (Admin)' },
          { id: 'e2', timestamp: timestamp, action: 'Sent', details: `Secure link sent to ${sendForm.email}` }
        ]
      };
      
      setAgreements(prev => [newAgreement, ...prev]);
      setIsSending(false);
      setIsSendModalOpen(false);
      setSendForm({ customerName: '', email: '', type: 'MSA' });
    }, 1500);
  };

  const handleSignAgreement = () => {
    if (!signingAgreement) return;
    setIsSigning(true);
    
    setTimeout(() => {
      const now = new Date();
      const timestamp = now.toLocaleString('en-IN', { hour: '2-digit', minute: '2-digit', day: 'numeric', month: 'short' });
      
      setAgreements(prev => prev.map(a => {
        if (a.id !== signingAgreement.id) return a;
        return {
          ...a,
          status: 'Signed',
          lastActivity: 'Signed just now',
          signedDocUrl: `signed_${a.type}_${a.customerName.replace(/\s/g, '_')}.pdf`.toLowerCase(),
          auditTrail: [
             ...a.auditTrail,
             { id: Math.random().toString(), timestamp: timestamp, action: 'Viewed', details: 'Document opened in Signing Room' },
             { id: Math.random().toString(), timestamp: timestamp, action: 'Signed', details: `Digitally signed by ${a.customerName} (Simulated)` },
             { id: Math.random().toString(), timestamp: timestamp, action: 'Sealed', details: 'Document locked and certified' }
          ]
        };
      }));
      setIsSigning(false);
      setSigningAgreement(null);
    }, 2000);
  };

  const copyLink = (link: string, id: string) => {
    navigator.clipboard.writeText(link);
    setCopiedLinkId(id);
    setTimeout(() => setCopiedLinkId(null), 2000);
  };

  // --- Render Functions ---

  const renderUploads = () => (
    <div className="space-y-6 animate-fade-in">
      <div 
        className={`p-8 border-2 border-dashed rounded-xl transition-colors text-center cursor-pointer
          ${dragActive ? "border-emerald-500 bg-emerald-50" : "border-slate-300 bg-slate-50 hover:bg-slate-100"}`}
        onDragEnter={handleDrag} onDragLeave={handleDrag} onDragOver={handleDrag} onDrop={handleDrop}
        onClick={() => document.getElementById('doc-upload')?.click()}
      >
        <div className="w-12 h-12 bg-white rounded-full shadow-sm flex items-center justify-center mx-auto mb-3 text-emerald-600">
            <Upload size={24} />
        </div>
        <p className="font-medium text-slate-700">Click to upload or drag and drop</p>
        <p className="text-sm text-slate-500 mt-1">Supported: JPEG, PNG, PDF</p>
        <input id="doc-upload" type="file" className="hidden" multiple onChange={handleFileInput} accept="image/jpeg,image/png,image/webp,application/pdf" />
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col">
        <div className="p-4 border-b border-slate-100 font-semibold text-slate-700 bg-slate-50/50 flex justify-between items-center">
           <span>Recent Uploads ({documents.length})</span>
           {documents.length > 0 && <button onClick={() => setDocuments([])} className="text-xs text-red-500 hover:text-red-600 font-medium">Clear All</button>}
        </div>
        
        <div className="overflow-y-auto p-4 space-y-3 max-h-[500px]">
          {documents.length === 0 ? (
             <div className="py-12 flex flex-col items-center justify-center text-slate-400">
                <FileText size={48} className="mb-3 opacity-50"/>
                <p>No documents uploaded yet.</p>
             </div>
          ) : (
            documents.map((doc) => (
              <div key={doc.id} className="border border-slate-200 rounded-lg p-4 flex gap-4 items-start hover:shadow-sm transition-shadow bg-white">
                 <div className="w-12 h-12 bg-slate-100 rounded-lg flex items-center justify-center flex-shrink-0 text-slate-500">
                    {doc.type === 'application/pdf' ? <FileText size={24} /> : <FileImage size={24} />}
                 </div>
                 <div className="flex-1 min-w-0">
                    <div className="flex justify-between items-start">
                       <div>
                          <h4 className="font-medium text-slate-800 truncate pr-4" title={doc.name}>{doc.name}</h4>
                          <p className="text-xs text-slate-500 mt-0.5">{formatBytes(doc.size)} • Uploaded {doc.uploadDate}</p>
                       </div>
                       <button onClick={() => setDocuments(prev => prev.filter(d => d.id !== doc.id))} className="text-slate-400 hover:text-red-500"><Trash2 size={16} /></button>
                    </div>
                    <div className="mt-3 pt-3 border-t border-slate-100">
                       {doc.ocrStatus === 'idle' && (
                          <div className="flex items-center justify-between">
                             <span className="text-xs text-slate-500">Analysis pending</span>
                             <button onClick={() => runOCR(doc.id)} className="flex items-center gap-2 text-xs font-medium bg-indigo-600 text-white px-3 py-1.5 rounded-md hover:bg-indigo-700 transition-colors">
                                <ScanLine size={14} /> Run Auto-OCR
                             </button>
                          </div>
                       )}
                       {doc.ocrStatus === 'processing' && <div className="flex items-center gap-2 text-xs text-indigo-600 font-medium"><Loader2 size={14} className="animate-spin" /> Extracting financial data with Gemini...</div>}
                       {doc.ocrStatus === 'completed' && doc.extractedData && (
                          <div className="bg-emerald-50/50 rounded-md p-3 border border-emerald-100">
                             <div className="flex items-center gap-2 mb-2 text-emerald-700 font-medium text-xs"><CheckCircle size={14} /> Data Extracted</div>
                             <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
                                <div><span className="block text-slate-400 mb-1">Vendor</span><span className="font-semibold text-slate-700">{doc.extractedData.vendor_name || 'N/A'}</span></div>
                                <div><span className="block text-slate-400 mb-1">Date</span><span className="font-semibold text-slate-700">{doc.extractedData.invoice_date || 'N/A'}</span></div>
                                <div><span className="block text-slate-400 mb-1">Total</span><span className="font-semibold text-slate-700">{formatCurrency(doc.extractedData.total_amount)}</span></div>
                                <div><span className="block text-slate-400 mb-1">GST</span><span className="font-semibold text-slate-700">{formatCurrency(doc.extractedData.gst_amount)}</span></div>
                             </div>
                             {doc.extractedData.summary && (
                               <div className="mt-3 text-xs bg-white p-3 rounded border border-emerald-100/50 shadow-sm">
                                  <div className="flex items-center gap-1.5 mb-1 text-slate-500 font-medium"><Info size={14} className="text-emerald-600"/><span>Document Summary</span></div>
                                  <p className="text-slate-700 leading-relaxed pl-5 border-l-2 border-emerald-200">{doc.extractedData.summary}</p>
                               </div>
                             )}
                          </div>
                       )}
                       {doc.ocrStatus === 'failed' && <div className="flex items-center gap-2 text-xs text-red-600 font-medium"><AlertCircle size={14} /> Failed to extract data.</div>}
                    </div>
                 </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );

  const renderTemplates = () => (
    <div className="space-y-6 animate-fade-in">
      <p className="text-sm text-slate-600">Select a pre-made, GST-compliant template for your next invoice.</p>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {MOCK_TEMPLATES.map(template => (
          <div key={template.id} className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden group hover:shadow-md transition-shadow cursor-pointer">
             <div className={`h-48 ${template.thumbnailColor} w-full flex items-center justify-center relative`}>
                <LayoutTemplate className="text-slate-400 opacity-50" size={48} />
                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/5 transition-colors flex items-center justify-center">
                   <button 
                     onClick={() => onUseTemplate?.(template.id)}
                     className="bg-white text-slate-800 px-4 py-2 rounded-full text-sm font-medium shadow-lg opacity-0 group-hover:opacity-100 transform translate-y-2 group-hover:translate-y-0 transition-all hover:bg-emerald-600 hover:text-white"
                   >
                     Use Template
                   </button>
                </div>
             </div>
             <div className="p-4">
                <h3 className="font-semibold text-slate-800">{template.name}</h3>
                <div className="flex flex-wrap gap-2 mt-2">
                  {template.tags.map(tag => (
                    <span key={tag} className="px-2 py-1 bg-slate-100 text-slate-500 text-[10px] rounded-full uppercase tracking-wide font-medium">{tag}</span>
                  ))}
                </div>
             </div>
          </div>
        ))}
      </div>
    </div>
  );

  const renderAgreements = () => {
    const viewingAudit = agreements.find(a => a.id === viewAuditId);

    return (
    <div className="space-y-6 animate-fade-in relative">
      
      {/* Mock Signing Modal */}
      {signingAgreement && (
        <div className="fixed inset-0 bg-slate-900 z-[60] flex flex-col animate-fade-in">
           {/* Header */}
           <div className="bg-white p-4 flex justify-between items-center shadow-md z-10">
              <div className="flex items-center gap-3">
                 <div className="w-8 h-8 bg-indigo-600 rounded text-white flex items-center justify-center font-bold">G</div>
                 <div className="h-6 w-px bg-slate-300"></div>
                 <div>
                    <h3 className="font-bold text-slate-800 text-sm">GRX10 Secure Sign</h3>
                    <p className="text-xs text-slate-500">Reviewing: {signingAgreement.type} for {signingAgreement.customerName}</p>
                 </div>
              </div>
              <button onClick={() => setSigningAgreement(null)} className="text-slate-500 hover:text-slate-800 text-sm font-medium">Cancel & Close</button>
           </div>

           {/* Document Body (Mock) */}
           <div className="flex-1 bg-slate-100 p-8 overflow-y-auto flex justify-center">
              <div className="bg-white shadow-xl w-full max-w-3xl min-h-[800px] p-12 text-slate-800 relative">
                  <h1 className="text-2xl font-bold uppercase text-center mb-8 border-b pb-4">{signingAgreement.type}</h1>
                  <div className="space-y-6 text-justify text-sm leading-relaxed">
                     <p>This Agreement is made on <strong>{new Date().toLocaleDateString()}</strong> between GRX10 Solutions and <strong>{signingAgreement.customerName}</strong>.</p>
                     <div className="h-4 bg-slate-100 rounded w-full"></div>
                     <div className="h-4 bg-slate-100 rounded w-5/6"></div>
                     <div className="h-4 bg-slate-100 rounded w-full"></div>
                     <p><strong>Terms and Conditions:</strong> The parties agree to the terms set forth in this document. This agreement is legally binding once signed.</p>
                     <div className="h-32 bg-slate-50 border-2 border-dashed border-slate-200 rounded flex items-center justify-center text-slate-400">
                        [Contract Body Content Placeholder]
                     </div>
                  </div>

                  <div className="mt-20 border-t pt-8 flex justify-between">
                      <div className="w-1/3">
                         <div className="h-12 border-b border-slate-900 mb-2"></div>
                         <p className="font-bold">Authorized Signatory</p>
                         <p className="text-xs text-slate-500">GRX10 Solutions Pvt Ltd</p>
                      </div>
                      <div className="w-1/3 relative group cursor-pointer" onClick={handleSignAgreement}>
                         <div className="h-12 border-b border-slate-900 mb-2 bg-yellow-50 flex items-center justify-center text-yellow-700 font-handwriting text-xl relative overflow-hidden">
                             {isSigning ? <Loader2 className="animate-spin text-indigo-600"/> : <span className="opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1 font-sans text-xs bg-indigo-600 text-white px-2 py-1 rounded shadow-lg absolute top-[-10px]">Click to Sign</span>}
                         </div>
                         <p className="font-bold">{signingAgreement.customerName}</p>
                         <p className="text-xs text-slate-500">Client / Customer</p>
                      </div>
                  </div>
              </div>
           </div>

           {/* Footer Action */}
           <div className="bg-white p-4 border-t border-slate-200 flex justify-end gap-4">
              <button onClick={() => setSigningAgreement(null)} className="px-6 py-2 text-slate-600 font-medium hover:bg-slate-50 rounded-lg">Decline</button>
              <button 
                 onClick={handleSignAgreement} 
                 disabled={isSigning}
                 className="bg-indigo-600 text-white px-8 py-2 rounded-lg font-bold hover:bg-indigo-700 shadow-lg shadow-indigo-200 flex items-center gap-2"
              >
                 {isSigning ? 'Securing Signature...' : 'Adopt & Sign'}
              </button>
           </div>
        </div>
      )}

      {/* Audit Trail Modal */}
      {viewingAudit && (
        <div className="fixed inset-0 bg-black/20 backdrop-blur-sm z-50 flex items-center justify-center p-4">
           <div className="bg-white rounded-xl shadow-xl max-w-lg w-full overflow-hidden animate-scale-in">
              <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                 <div>
                   <h3 className="font-bold text-slate-800 flex items-center gap-2"><History size={18} className="text-indigo-600"/> Audit Trail</h3>
                   <p className="text-xs text-slate-500">{viewingAudit.uniqueLink}</p>
                 </div>
                 <button onClick={() => setViewAuditId(null)} className="text-slate-400 hover:text-slate-600"><X size={20}/></button>
              </div>
              <div className="p-6 max-h-[400px] overflow-y-auto bg-white">
                 <div className="relative border-l-2 border-indigo-100 ml-3 space-y-8 pl-6 pb-2">
                    {viewingAudit.auditTrail.map((event, idx) => (
                      <div key={event.id} className="relative">
                         <span className={`absolute -left-[31px] w-4 h-4 rounded-full border-2 border-white shadow-sm 
                           ${idx === viewingAudit.auditTrail.length - 1 ? 'bg-indigo-600' : 'bg-slate-300'}`}></span>
                         <p className="text-xs font-semibold text-slate-500 mb-0.5">{event.timestamp}</p>
                         <h4 className="text-sm font-bold text-slate-800">{event.action}</h4>
                         <p className="text-sm text-slate-600 mt-1">{event.details}</p>
                      </div>
                    ))}
                 </div>
              </div>
           </div>
        </div>
      )}

      {/* Send Modal */}
      {isSendModalOpen && (
         <div className="fixed inset-0 bg-black/20 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-xl shadow-xl max-w-md w-full p-6 animate-scale-in">
                <div className="flex justify-between items-center mb-4">
                    <h3 className="text-lg font-bold text-slate-800">Send Agreement</h3>
                    <button onClick={() => setIsSendModalOpen(false)} className="text-slate-400 hover:text-slate-600"><X size={20}/></button>
                </div>
                <div className="space-y-4">
                    <div>
                        <label className="block text-xs font-semibold text-slate-500 mb-1">Customer Name</label>
                        <input type="text" className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none" placeholder="e.g. TechFlow India" value={sendForm.customerName} onChange={e => setSendForm({...sendForm, customerName: e.target.value})} />
                    </div>
                    <div>
                        <label className="block text-xs font-semibold text-slate-500 mb-1">Recipient Email</label>
                        <input type="email" className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none" placeholder="signer@company.com" value={sendForm.email} onChange={e => setSendForm({...sendForm, email: e.target.value})} />
                    </div>
                     <div>
                        <label className="block text-xs font-semibold text-slate-500 mb-1">Agreement Type</label>
                        <select className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none bg-white" value={sendForm.type} onChange={e => setSendForm({...sendForm, type: e.target.value})}>
                            <option value="MSA">Master Services Agreement (MSA)</option>
                            <option value="NDA">Non-Disclosure Agreement (NDA)</option>
                            <option value="Service Contract">Service Contract</option>
                        </select>
                    </div>
                    <button onClick={handleSendAgreement} disabled={isSending || !sendForm.customerName || !sendForm.email} className="w-full bg-indigo-600 text-white rounded-lg py-2.5 font-medium hover:bg-indigo-700 transition-colors flex items-center justify-center gap-2 disabled:opacity-70">
                        {isSending ? <Loader2 className="animate-spin" size={18} /> : <Send size={18} />}
                        {isSending ? 'Generating Secure Link...' : 'Send for Signature'}
                    </button>
                </div>
            </div>
         </div>
       )}

      <div className="flex justify-between items-center">
         <div className="flex flex-col gap-1">
            <p className="text-sm text-slate-600">Manage e-signatures and contracts sent to customers.</p>
            <div className="flex items-center gap-2 text-xs text-emerald-600 bg-emerald-50 px-2 py-1 rounded-md border border-emerald-100 w-fit">
                <Wifi size={12} className="animate-pulse" /> Real-time Tracking Active
            </div>
         </div>
         <button onClick={() => setIsSendModalOpen(true)} className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-indigo-700 transition-colors shadow-sm shadow-indigo-200">
           <FileSignature size={16} /> New Agreement
         </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <table className="w-full text-sm text-left">
          <thead className="bg-slate-50 text-slate-500 font-medium border-b border-slate-100">
            <tr>
              <th className="px-6 py-4">Customer & Details</th>
              <th className="px-6 py-4">Status</th>
              <th className="px-6 py-4">Secure Link</th>
              <th className="px-6 py-4">Activity</th>
              <th className="px-6 py-4 text-center">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {agreements.map((agreement) => (
              <tr key={agreement.id} className="hover:bg-slate-50 transition-colors duration-300">
                <td className="px-6 py-4">
                   <div className="font-medium text-slate-800">{agreement.customerName}</div>
                   <div className="text-xs text-slate-500">{agreement.type} • {agreement.recipientEmail}</div>
                </td>
                <td className="px-6 py-4">
                   <span className={`px-2.5 py-0.5 rounded-full text-xs font-medium border flex items-center gap-1 w-fit transition-all duration-300
                     ${agreement.status === 'Signed' ? 'bg-emerald-100 text-emerald-700 border-emerald-200' : 
                       agreement.status === 'Viewed' ? 'bg-blue-100 text-blue-700 border-blue-200' : 
                       agreement.status === 'Expired' ? 'bg-slate-100 text-slate-500 border-slate-200' :
                       'bg-amber-100 text-amber-700 border-amber-200'}`}>
                     {agreement.status === 'Signed' && <ShieldCheck size={12}/>}
                     {agreement.status === 'Viewed' && <Eye size={12}/>}
                     {agreement.status === 'Sent' && <Clock size={12}/>}
                     {agreement.status === 'Expired' && <X size={12}/>}
                     {agreement.status}
                   </span>
                </td>
                <td className="px-6 py-4">
                   <div className="flex items-center gap-2">
                    <button onClick={() => copyLink(agreement.uniqueLink, agreement.id)} className="flex items-center gap-2 text-xs bg-white border border-slate-200 px-2 py-1 rounded hover:bg-slate-50 text-slate-600 transition-colors" title="Copy Link">
                       <Link size={12} /> {copiedLinkId === agreement.id ? 'Copied!' : 'Copy'}
                    </button>
                    {agreement.status !== 'Signed' && agreement.status !== 'Expired' && (
                        <button onClick={() => setSigningAgreement(agreement)} className="flex items-center gap-1 text-xs text-indigo-600 hover:text-indigo-800 font-medium px-2 py-1 hover:bg-indigo-50 rounded" title="Simulate Customer View">
                           <ExternalLink size={12} /> Open Sign Link
                        </button>
                    )}
                   </div>
                </td>
                <td className="px-6 py-4 text-slate-500 text-xs">{agreement.lastActivity}</td>
                <td className="px-6 py-4 text-center flex justify-center gap-2">
                   <button onClick={() => setViewAuditId(agreement.id)} className="text-slate-500 hover:text-indigo-600 p-2 rounded-full hover:bg-indigo-50 transition-colors" title="View Audit Trail">
                      <History size={16} />
                   </button>
                   {agreement.status === 'Signed' ? (
                      <button className="text-slate-500 hover:text-emerald-600 p-2 rounded-full hover:bg-emerald-50 transition-colors" title="Download Signed PDF">
                         <Download size={16} />
                      </button>
                   ) : (
                      <div className="w-8"></div>
                   )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
    );
  };

  const renderMSA = () => (
    <div className="animate-fade-in bg-white rounded-xl shadow-sm border border-slate-200 p-8 max-w-4xl mx-auto">
      <div className="flex justify-between items-start mb-8 pb-8 border-b border-slate-100">
         <div>
           <h1 className="text-2xl font-bold text-slate-900">Master Services Agreement</h1>
           <p className="text-slate-500 text-sm mt-1">Reference Version 1.4 • Updated Jan 2024</p>
         </div>
         <button onClick={() => window.print()} className="text-indigo-600 text-sm font-medium border border-indigo-200 px-4 py-2 rounded-lg hover:bg-indigo-50">Download PDF</button>
      </div>
      <div className="prose prose-slate prose-sm max-w-none text-justify text-slate-700 space-y-4">
        <p><strong>1. PARTIES.</strong> This Master Services Agreement (hereinafter referred to as "Agreement") is entered into by and between GRX10 Solutions Pvt Ltd (the "Service Provider") and the Client (the "Customer").</p>
        <p><strong>2. SERVICES.</strong> Service Provider agrees to perform for Customer the services listed in the applicable Statement of Work (SOW). All Services shall be performed in a professional manner.</p>
        <p><strong>3. PAYMENT TERMS.</strong> Invoices will be issued upon completion of milestones. Payment shall be made within 30 days of invoice date.</p>
        <p><strong>4. CONFIDENTIALITY.</strong> Each party acknowledges that it will have access to certain confidential information.</p>
        <p><strong>5. GOVERNING LAW.</strong> This Agreement shall be governed by the laws of India.</p>
      </div>
      <div className="mt-12 p-6 bg-slate-50 rounded-lg border border-slate-200">
         <h4 className="font-semibold text-slate-800 text-sm mb-2">Usage Note</h4>
         <p className="text-xs text-slate-500">To send this to a customer for signature, please go to the "Agreements & E-Sign" tab.</p>
      </div>
    </div>
  );

  return (
    <div className="space-y-6 h-full flex flex-col">
       <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Document Hub</h2>
          <p className="text-slate-500">Central repository for receipts, templates, and legal agreements.</p>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 bg-slate-100 p-1 rounded-xl w-fit">
         <button onClick={() => setActiveTab('uploads')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-2 ${activeTab === 'uploads' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}><Upload size={16}/> Uploads & OCR</button>
         <button onClick={() => setActiveTab('templates')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-2 ${activeTab === 'templates' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}><LayoutTemplate size={16}/> Invoice Templates</button>
         <button onClick={() => setActiveTab('agreements')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-2 ${activeTab === 'agreements' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}><PenTool size={16}/> Agreements & E-Sign</button>
         <button onClick={() => setActiveTab('msa')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-2 ${activeTab === 'msa' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}><BookOpen size={16}/> MSA Reference</button>
      </div>

      {/* Content Area */}
      <div className="flex-1">
         {activeTab === 'uploads' && renderUploads()}
         {activeTab === 'templates' && renderTemplates()}
         {activeTab === 'agreements' && renderAgreements()}
         {activeTab === 'msa' && renderMSA()}
      </div>
    </div>
  );
};

export default Documents;
