/**
 * Finance Models - Double-Entry General Ledger System
 *
 * Architecture: All financial documents generate journal entries that post to the GL.
 * Reports read exclusively from posted GL data. Financial data is append-only.
 *
 * Invariants enforced:
 * - Every JournalEntry must have SUM(debits) = SUM(credits)
 * - Posted journal entries cannot be modified, only reversed
 * - Accounting periods can be locked to prevent backdated entries
 * - All amounts use DECIMAL(20,6) for precision
 * - All financial records have audit fields (createdBy, updatedBy)
 */

import { DataTypes } from 'sequelize';

export function defineFinanceModels(sequelize) {
    // ============================================
    // FISCAL YEARS & ACCOUNTING PERIODS
    // ============================================

    const FiscalYear = sequelize.define('FiscalYear', {
        id: { type: DataTypes.STRING, primaryKey: true },
        name: { type: DataTypes.STRING, allowNull: false }, // e.g., "FY 2025-26"
        startDate: { type: DataTypes.STRING, allowNull: false }, // YYYY-MM-DD
        endDate: { type: DataTypes.STRING, allowNull: false },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Open',
            validate: { isIn: [['Open', 'Closed', 'Locked']] }
        },
        isActive: { type: DataTypes.BOOLEAN, defaultValue: true },
        closedBy: { type: DataTypes.STRING },
        closedAt: { type: DataTypes.STRING }
    }, {
        tableName: 'fiscal_years',
        indexes: [{ fields: ['startDate', 'endDate'] }]
    });

    const AccountingPeriod = sequelize.define('AccountingPeriod', {
        id: { type: DataTypes.STRING, primaryKey: true },
        fiscalYearId: { type: DataTypes.STRING, allowNull: false },
        name: { type: DataTypes.STRING, allowNull: false }, // e.g., "April 2025"
        periodNumber: { type: DataTypes.INTEGER, allowNull: false }, // 1-12
        startDate: { type: DataTypes.STRING, allowNull: false },
        endDate: { type: DataTypes.STRING, allowNull: false },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Open',
            validate: { isIn: [['Open', 'Closed', 'Locked']] }
        },
        closedBy: { type: DataTypes.STRING },
        closedAt: { type: DataTypes.STRING }
    }, {
        tableName: 'accounting_periods',
        indexes: [
            { fields: ['fiscalYearId'] },
            { fields: ['startDate', 'endDate'] },
            { unique: true, fields: ['fiscalYearId', 'periodNumber'] }
        ]
    });

    // ============================================
    // JOURNAL ENTRIES - THE HEART OF DOUBLE-ENTRY GL
    // ============================================

    const JournalEntry = sequelize.define('JournalEntry', {
        id: { type: DataTypes.STRING, primaryKey: true },
        number: { type: DataTypes.STRING, allowNull: false, unique: true }, // JE-00001
        date: { type: DataTypes.STRING, allowNull: false }, // Transaction date
        description: { type: DataTypes.STRING, allowNull: false },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Draft',
            validate: { isIn: [['Draft', 'Approved', 'Posted', 'Reversed']] }
        },
        // Source document tracking
        sourceDocument: { type: DataTypes.STRING }, // 'Invoice', 'Bill', 'Payment', 'CreditNote', 'Manual', etc.
        sourceDocumentId: { type: DataTypes.STRING },
        // Period linkage
        periodId: { type: DataTypes.STRING },
        // Currency (future multi-currency support)
        currencyCode: { type: DataTypes.STRING, defaultValue: 'INR' },
        exchangeRate: { type: DataTypes.DECIMAL(20, 6), defaultValue: 1.000000 },
        // Totals (denormalized for quick reference, validated against lines)
        totalDebit: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        totalCredit: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        // Reversal tracking
        reversalOf: { type: DataTypes.STRING }, // ID of JE this reverses
        reversedBy: { type: DataTypes.STRING }, // ID of JE that reversed this
        reversalDate: { type: DataTypes.STRING },
        reversalReason: { type: DataTypes.STRING },
        // Auto-generated vs manual
        isAutoGenerated: { type: DataTypes.BOOLEAN, defaultValue: false },
        // Audit fields
        createdBy: { type: DataTypes.STRING },
        approvedBy: { type: DataTypes.STRING },
        approvedAt: { type: DataTypes.STRING },
        postedBy: { type: DataTypes.STRING },
        postedAt: { type: DataTypes.STRING },
        // Idempotency
        idempotencyKey: { type: DataTypes.STRING, unique: true },
        // Notes / memo
        notes: { type: DataTypes.TEXT }
    }, {
        tableName: 'journal_entries',
        indexes: [
            { fields: ['date'] },
            { fields: ['status'] },
            { fields: ['sourceDocument', 'sourceDocumentId'] },
            { fields: ['periodId'] },
            { fields: ['reversalOf'] }
        ]
    });

    const JournalEntryLine = sequelize.define('JournalEntryLine', {
        id: { type: DataTypes.STRING, primaryKey: true },
        journalEntryId: { type: DataTypes.STRING, allowNull: false },
        lineNumber: { type: DataTypes.INTEGER, allowNull: false },
        accountId: { type: DataTypes.STRING, allowNull: false }, // ChartOfAccount ID
        description: { type: DataTypes.STRING },
        debitAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        creditAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        // Dimensions for reporting
        costCenterId: { type: DataTypes.STRING },
        projectId: { type: DataTypes.STRING },
        // Tax linkage
        taxCodeId: { type: DataTypes.STRING },
        taxAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        // Entity reference (customer/vendor for subledger)
        entityType: { type: DataTypes.STRING }, // 'Customer', 'Vendor'
        entityId: { type: DataTypes.STRING }
    }, {
        tableName: 'journal_entry_lines',
        indexes: [
            { fields: ['journalEntryId'] },
            { fields: ['accountId'] },
            { fields: ['costCenterId'] },
            { fields: ['projectId'] },
            { fields: ['entityType', 'entityId'] }
        ]
    });

    // ============================================
    // DIMENSIONS (Cost Centers & Projects)
    // ============================================

    const CostCenter = sequelize.define('CostCenter', {
        id: { type: DataTypes.STRING, primaryKey: true },
        code: { type: DataTypes.STRING, allowNull: false, unique: true },
        name: { type: DataTypes.STRING, allowNull: false },
        description: { type: DataTypes.TEXT },
        parentId: { type: DataTypes.STRING },
        isActive: { type: DataTypes.BOOLEAN, defaultValue: true }
    }, { tableName: 'cost_centers' });

    const Project = sequelize.define('Project', {
        id: { type: DataTypes.STRING, primaryKey: true },
        code: { type: DataTypes.STRING, allowNull: false, unique: true },
        name: { type: DataTypes.STRING, allowNull: false },
        customerId: { type: DataTypes.STRING },
        description: { type: DataTypes.TEXT },
        startDate: { type: DataTypes.STRING },
        endDate: { type: DataTypes.STRING },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Active',
            validate: { isIn: [['Active', 'Completed', 'OnHold', 'Cancelled']] }
        },
        budgetAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        isActive: { type: DataTypes.BOOLEAN, defaultValue: true }
    }, { tableName: 'projects' });

    // ============================================
    // VENDORS (Procure-to-Pay)
    // ============================================

    const Vendor = sequelize.define('Vendor', {
        id: { type: DataTypes.STRING, primaryKey: true },
        code: { type: DataTypes.STRING, unique: true },
        name: { type: DataTypes.STRING, allowNull: false },
        gstin: { type: DataTypes.STRING },
        pan: { type: DataTypes.STRING },
        email: { type: DataTypes.STRING },
        phone: { type: DataTypes.STRING },
        address: { type: DataTypes.TEXT },
        city: { type: DataTypes.STRING },
        state: { type: DataTypes.STRING },
        pincode: { type: DataTypes.STRING },
        country: { type: DataTypes.STRING, defaultValue: 'India' },
        // Payment terms
        paymentTermsDays: { type: DataTypes.INTEGER, defaultValue: 30 },
        creditLimit: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        // Default accounts
        defaultExpenseAccountId: { type: DataTypes.STRING },
        // Balances (denormalized, reconciled from GL)
        balance: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        // Bank details
        bankAccountNumber: { type: DataTypes.STRING },
        bankIFSC: { type: DataTypes.STRING },
        bankName: { type: DataTypes.STRING },
        // Status
        isActive: { type: DataTypes.BOOLEAN, defaultValue: true },
        notes: { type: DataTypes.TEXT }
    }, {
        tableName: 'vendors',
        indexes: [{ fields: ['name'] }, { fields: ['gstin'] }]
    });

    // ============================================
    // ESTIMATES (Order-to-Cash: Step 1)
    // ============================================

    const Estimate = sequelize.define('Estimate', {
        id: { type: DataTypes.STRING, primaryKey: true },
        number: { type: DataTypes.STRING, allowNull: false, unique: true },
        customerId: { type: DataTypes.STRING, allowNull: false },
        customerName: { type: DataTypes.STRING },
        date: { type: DataTypes.STRING, allowNull: false },
        expiryDate: { type: DataTypes.STRING },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Draft',
            validate: { isIn: [['Draft', 'Sent', 'Accepted', 'Declined', 'Invoiced', 'Expired']] }
        },
        subTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        total: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        notes: { type: DataTypes.TEXT },
        termsAndConditions: { type: DataTypes.TEXT },
        createdBy: { type: DataTypes.STRING }
    }, {
        tableName: 'estimates',
        indexes: [{ fields: ['customerId'] }, { fields: ['date'] }, { fields: ['status'] }]
    });

    const EstimateItem = sequelize.define('EstimateItem', {
        id: { type: DataTypes.STRING, primaryKey: true },
        estimateId: { type: DataTypes.STRING, allowNull: false },
        description: { type: DataTypes.STRING },
        hsn: { type: DataTypes.STRING },
        accountId: { type: DataTypes.STRING },
        quantity: { type: DataTypes.DECIMAL(20, 6), defaultValue: 1 },
        rate: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxCodeId: { type: DataTypes.STRING },
        taxRate: { type: DataTypes.DECIMAL(10, 4), defaultValue: 0 },
        taxAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 }
    }, { tableName: 'estimate_items' });

    // ============================================
    // SALES ORDERS (Order-to-Cash: Step 2)
    // ============================================

    const SalesOrder = sequelize.define('SalesOrder', {
        id: { type: DataTypes.STRING, primaryKey: true },
        number: { type: DataTypes.STRING, allowNull: false, unique: true },
        customerId: { type: DataTypes.STRING, allowNull: false },
        customerName: { type: DataTypes.STRING },
        estimateId: { type: DataTypes.STRING }, // Link to source estimate
        date: { type: DataTypes.STRING, allowNull: false },
        expectedDeliveryDate: { type: DataTypes.STRING },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Draft',
            validate: { isIn: [['Draft', 'Confirmed', 'Fulfilled', 'Cancelled']] }
        },
        subTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        total: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        notes: { type: DataTypes.TEXT },
        createdBy: { type: DataTypes.STRING }
    }, {
        tableName: 'sales_orders',
        indexes: [{ fields: ['customerId'] }, { fields: ['estimateId'] }]
    });

    const SalesOrderItem = sequelize.define('SalesOrderItem', {
        id: { type: DataTypes.STRING, primaryKey: true },
        salesOrderId: { type: DataTypes.STRING, allowNull: false },
        description: { type: DataTypes.STRING },
        hsn: { type: DataTypes.STRING },
        accountId: { type: DataTypes.STRING },
        quantity: { type: DataTypes.DECIMAL(20, 6), defaultValue: 1 },
        rate: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxCodeId: { type: DataTypes.STRING },
        taxRate: { type: DataTypes.DECIMAL(10, 4), defaultValue: 0 },
        taxAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 }
    }, { tableName: 'sales_order_items' });

    // ============================================
    // CREDIT NOTES (Order-to-Cash: Returns)
    // ============================================

    const CreditNote = sequelize.define('CreditNote', {
        id: { type: DataTypes.STRING, primaryKey: true },
        number: { type: DataTypes.STRING, allowNull: false, unique: true },
        customerId: { type: DataTypes.STRING, allowNull: false },
        customerName: { type: DataTypes.STRING },
        originalInvoiceId: { type: DataTypes.STRING },
        date: { type: DataTypes.STRING, allowNull: false },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Draft',
            validate: { isIn: [['Draft', 'Approved', 'Applied', 'Void']] }
        },
        subTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        total: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amountApplied: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        balanceRemaining: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        journalEntryId: { type: DataTypes.STRING },
        reason: { type: DataTypes.TEXT },
        notes: { type: DataTypes.TEXT },
        createdBy: { type: DataTypes.STRING }
    }, {
        tableName: 'credit_notes',
        indexes: [{ fields: ['customerId'] }, { fields: ['originalInvoiceId'] }]
    });

    const CreditNoteItem = sequelize.define('CreditNoteItem', {
        id: { type: DataTypes.STRING, primaryKey: true },
        creditNoteId: { type: DataTypes.STRING, allowNull: false },
        description: { type: DataTypes.STRING },
        hsn: { type: DataTypes.STRING },
        accountId: { type: DataTypes.STRING },
        quantity: { type: DataTypes.DECIMAL(20, 6), defaultValue: 1 },
        rate: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxCodeId: { type: DataTypes.STRING },
        taxRate: { type: DataTypes.DECIMAL(10, 4), defaultValue: 0 },
        taxAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 }
    }, { tableName: 'credit_note_items' });

    // ============================================
    // BILLS (Procure-to-Pay)
    // ============================================

    const Bill = sequelize.define('Bill', {
        id: { type: DataTypes.STRING, primaryKey: true },
        number: { type: DataTypes.STRING, allowNull: false, unique: true },
        vendorId: { type: DataTypes.STRING, allowNull: false },
        vendorName: { type: DataTypes.STRING },
        vendorInvoiceNumber: { type: DataTypes.STRING }, // Vendor's own invoice number
        date: { type: DataTypes.STRING, allowNull: false },
        dueDate: { type: DataTypes.STRING },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Draft',
            validate: { isIn: [['Draft', 'Approved', 'Overdue', 'PartiallyPaid', 'Paid', 'Void']] }
        },
        subTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        total: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amountPaid: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        balanceDue: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        journalEntryId: { type: DataTypes.STRING },
        notes: { type: DataTypes.TEXT },
        createdBy: { type: DataTypes.STRING }
    }, {
        tableName: 'bills',
        indexes: [{ fields: ['vendorId'] }, { fields: ['date'] }, { fields: ['status'] }, { fields: ['dueDate'] }]
    });

    const BillItem = sequelize.define('BillItem', {
        id: { type: DataTypes.STRING, primaryKey: true },
        billId: { type: DataTypes.STRING, allowNull: false },
        accountId: { type: DataTypes.STRING }, // Expense/asset account
        description: { type: DataTypes.STRING },
        hsn: { type: DataTypes.STRING },
        quantity: { type: DataTypes.DECIMAL(20, 6), defaultValue: 1 },
        rate: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxCodeId: { type: DataTypes.STRING },
        taxRate: { type: DataTypes.DECIMAL(10, 4), defaultValue: 0 },
        taxAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 }
    }, { tableName: 'bill_items' });

    // ============================================
    // VENDOR CREDITS
    // ============================================

    const VendorCredit = sequelize.define('VendorCredit', {
        id: { type: DataTypes.STRING, primaryKey: true },
        number: { type: DataTypes.STRING, allowNull: false, unique: true },
        vendorId: { type: DataTypes.STRING, allowNull: false },
        vendorName: { type: DataTypes.STRING },
        originalBillId: { type: DataTypes.STRING },
        date: { type: DataTypes.STRING, allowNull: false },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Draft',
            validate: { isIn: [['Draft', 'Approved', 'Applied', 'Void']] }
        },
        subTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxTotal: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        total: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amountApplied: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        balanceRemaining: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        journalEntryId: { type: DataTypes.STRING },
        reason: { type: DataTypes.TEXT },
        notes: { type: DataTypes.TEXT },
        createdBy: { type: DataTypes.STRING }
    }, {
        tableName: 'vendor_credits',
        indexes: [{ fields: ['vendorId'] }, { fields: ['originalBillId'] }]
    });

    const VendorCreditItem = sequelize.define('VendorCreditItem', {
        id: { type: DataTypes.STRING, primaryKey: true },
        vendorCreditId: { type: DataTypes.STRING, allowNull: false },
        accountId: { type: DataTypes.STRING },
        description: { type: DataTypes.STRING },
        hsn: { type: DataTypes.STRING },
        quantity: { type: DataTypes.DECIMAL(20, 6), defaultValue: 1 },
        rate: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        taxCodeId: { type: DataTypes.STRING },
        taxRate: { type: DataTypes.DECIMAL(10, 4), defaultValue: 0 },
        taxAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 }
    }, { tableName: 'vendor_credit_items' });

    // ============================================
    // PAYMENTS (Unified for Customers & Vendors)
    // ============================================

    const Payment = sequelize.define('Payment', {
        id: { type: DataTypes.STRING, primaryKey: true },
        number: { type: DataTypes.STRING, allowNull: false, unique: true },
        date: { type: DataTypes.STRING, allowNull: false },
        type: {
            type: DataTypes.STRING,
            allowNull: false,
            validate: { isIn: [['CustomerPayment', 'VendorPayment']] }
        },
        // One of these will be set based on type
        customerId: { type: DataTypes.STRING },
        vendorId: { type: DataTypes.STRING },
        amount: { type: DataTypes.DECIMAL(20, 6), allowNull: false },
        // Payment details
        paymentMethod: { type: DataTypes.STRING, defaultValue: 'BankTransfer' }, // BankTransfer, Cash, Cheque, UPI, Card
        bankAccountId: { type: DataTypes.STRING }, // Which bank account
        referenceNumber: { type: DataTypes.STRING }, // Cheque number, UTR, etc.
        // Status
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Draft',
            validate: { isIn: [['Draft', 'Confirmed', 'Void']] }
        },
        // Allocation tracking
        amountAllocated: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        amountUnallocated: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        // GL linkage
        journalEntryId: { type: DataTypes.STRING },
        // Overpayment handling
        isOverpayment: { type: DataTypes.BOOLEAN, defaultValue: false },
        overpaymentAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        // Audit
        notes: { type: DataTypes.TEXT },
        createdBy: { type: DataTypes.STRING },
        confirmedBy: { type: DataTypes.STRING },
        confirmedAt: { type: DataTypes.STRING }
    }, {
        tableName: 'payments',
        indexes: [
            { fields: ['type'] },
            { fields: ['customerId'] },
            { fields: ['vendorId'] },
            { fields: ['date'] },
            { fields: ['status'] },
            { fields: ['bankAccountId'] }
        ]
    });

    const PaymentAllocation = sequelize.define('PaymentAllocation', {
        id: { type: DataTypes.STRING, primaryKey: true },
        paymentId: { type: DataTypes.STRING, allowNull: false },
        documentType: {
            type: DataTypes.STRING,
            allowNull: false,
            validate: { isIn: [['Invoice', 'Bill', 'CreditNote', 'VendorCredit']] }
        },
        documentId: { type: DataTypes.STRING, allowNull: false },
        amount: { type: DataTypes.DECIMAL(20, 6), allowNull: false }
    }, {
        tableName: 'payment_allocations',
        indexes: [
            { fields: ['paymentId'] },
            { fields: ['documentType', 'documentId'] }
        ]
    });

    // ============================================
    // TAX ENGINE
    // ============================================

    const TaxGroup = sequelize.define('TaxGroup', {
        id: { type: DataTypes.STRING, primaryKey: true },
        name: { type: DataTypes.STRING, allowNull: false, unique: true }, // e.g., "GST 18%"
        description: { type: DataTypes.TEXT },
        isActive: { type: DataTypes.BOOLEAN, defaultValue: true }
    }, { tableName: 'tax_groups' });

    const TaxCode = sequelize.define('TaxCode', {
        id: { type: DataTypes.STRING, primaryKey: true },
        code: { type: DataTypes.STRING, allowNull: false, unique: true }, // e.g., "CGST_9", "SGST_9", "IGST_18"
        name: { type: DataTypes.STRING, allowNull: false }, // e.g., "CGST @ 9%"
        rate: { type: DataTypes.DECIMAL(10, 4), allowNull: false }, // 9.0000 for 9%
        type: {
            type: DataTypes.STRING,
            defaultValue: 'Percentage',
            validate: { isIn: [['Percentage', 'Fixed']] }
        },
        isInclusive: { type: DataTypes.BOOLEAN, defaultValue: false }, // Tax inclusive pricing
        taxGroupId: { type: DataTypes.STRING }, // Which group this belongs to
        // Ledger accounts for this tax
        salesAccountId: { type: DataTypes.STRING }, // Output tax liability account
        purchaseAccountId: { type: DataTypes.STRING }, // Input tax credit account
        isActive: { type: DataTypes.BOOLEAN, defaultValue: true }
    }, {
        tableName: 'tax_codes',
        indexes: [{ fields: ['taxGroupId'] }]
    });

    const TaxGroupTax = sequelize.define('TaxGroupTax', {
        id: { type: DataTypes.STRING, primaryKey: true },
        taxGroupId: { type: DataTypes.STRING, allowNull: false },
        taxCodeId: { type: DataTypes.STRING, allowNull: false }
    }, {
        tableName: 'tax_group_taxes',
        indexes: [{ unique: true, fields: ['taxGroupId', 'taxCodeId'] }]
    });

    // ============================================
    // BANKING & RECONCILIATION
    // ============================================

    const BankAccount = sequelize.define('BankAccount', {
        id: { type: DataTypes.STRING, primaryKey: true },
        name: { type: DataTypes.STRING, allowNull: false },
        accountNumber: { type: DataTypes.STRING },
        bankName: { type: DataTypes.STRING },
        branchName: { type: DataTypes.STRING },
        ifsc: { type: DataTypes.STRING },
        accountType: {
            type: DataTypes.STRING,
            defaultValue: 'Current',
            validate: { isIn: [['Savings', 'Current', 'CashOnHand', 'CreditCard']] }
        },
        // Link to Chart of Accounts
        chartOfAccountId: { type: DataTypes.STRING, allowNull: false },
        // Balances
        currentBalance: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        bankBalance: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 }, // As per bank statement
        // Status
        isActive: { type: DataTypes.BOOLEAN, defaultValue: true },
        isDefault: { type: DataTypes.BOOLEAN, defaultValue: false }
    }, {
        tableName: 'bank_accounts',
        indexes: [{ fields: ['chartOfAccountId'] }]
    });

    const BankStatement = sequelize.define('BankStatement', {
        id: { type: DataTypes.STRING, primaryKey: true },
        bankAccountId: { type: DataTypes.STRING, allowNull: false },
        statementDate: { type: DataTypes.STRING, allowNull: false },
        fileName: { type: DataTypes.STRING },
        openingBalance: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        closingBalance: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        totalDebit: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        totalCredit: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        transactionCount: { type: DataTypes.INTEGER, defaultValue: 0 },
        importedAt: { type: DataTypes.STRING },
        importedBy: { type: DataTypes.STRING }
    }, {
        tableName: 'bank_statements',
        indexes: [{ fields: ['bankAccountId'] }]
    });

    const BankTransaction = sequelize.define('BankTransaction', {
        id: { type: DataTypes.STRING, primaryKey: true },
        bankAccountId: { type: DataTypes.STRING, allowNull: false },
        statementId: { type: DataTypes.STRING },
        date: { type: DataTypes.STRING, allowNull: false },
        description: { type: DataTypes.STRING },
        reference: { type: DataTypes.STRING },
        debit: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        credit: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        runningBalance: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        // Reconciliation
        isReconciled: { type: DataTypes.BOOLEAN, defaultValue: false },
        reconciledAt: { type: DataTypes.STRING },
        reconciledBy: { type: DataTypes.STRING },
        // Manual or auto match
        matchType: { type: DataTypes.STRING }, // 'Auto', 'Manual', null
        matchedJournalEntryId: { type: DataTypes.STRING },
        matchedPaymentId: { type: DataTypes.STRING },
        // Categorization for unmatched
        categoryAccountId: { type: DataTypes.STRING },
        // Status
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Unmatched',
            validate: { isIn: [['Unmatched', 'Matched', 'Reconciled', 'Excluded']] }
        }
    }, {
        tableName: 'bank_transactions',
        indexes: [
            { fields: ['bankAccountId'] },
            { fields: ['date'] },
            { fields: ['isReconciled'] },
            { fields: ['status'] }
        ]
    });

    // ============================================
    // BUDGETS
    // ============================================

    const Budget = sequelize.define('Budget', {
        id: { type: DataTypes.STRING, primaryKey: true },
        name: { type: DataTypes.STRING, allowNull: false },
        fiscalYearId: { type: DataTypes.STRING },
        status: {
            type: DataTypes.STRING,
            defaultValue: 'Draft',
            validate: { isIn: [['Draft', 'Active', 'Closed']] }
        },
        description: { type: DataTypes.TEXT },
        createdBy: { type: DataTypes.STRING },
        approvedBy: { type: DataTypes.STRING },
        approvedAt: { type: DataTypes.STRING }
    }, { tableName: 'budgets' });

    const BudgetLine = sequelize.define('BudgetLine', {
        id: { type: DataTypes.STRING, primaryKey: true },
        budgetId: { type: DataTypes.STRING, allowNull: false },
        accountId: { type: DataTypes.STRING, allowNull: false },
        costCenterId: { type: DataTypes.STRING },
        projectId: { type: DataTypes.STRING },
        // Monthly amounts (period 1-12)
        period1: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period2: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period3: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period4: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period5: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period6: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period7: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period8: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period9: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period10: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period11: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        period12: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 },
        totalAmount: { type: DataTypes.DECIMAL(20, 6), defaultValue: 0 }
    }, {
        tableName: 'budget_lines',
        indexes: [{ fields: ['budgetId'] }, { fields: ['accountId'] }]
    });

    // ============================================
    // AUDIT LOG (Immutable)
    // ============================================

    const AuditLog = sequelize.define('AuditLog', {
        id: { type: DataTypes.STRING, primaryKey: true },
        tableName: { type: DataTypes.STRING, allowNull: false },
        recordId: { type: DataTypes.STRING, allowNull: false },
        action: {
            type: DataTypes.STRING,
            allowNull: false,
            validate: { isIn: [['CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'POST', 'REVERSE', 'VOID', 'LOCK', 'RECONCILE']] }
        },
        userId: { type: DataTypes.STRING },
        userName: { type: DataTypes.STRING },
        timestamp: { type: DataTypes.STRING, allowNull: false },
        previousValues: { type: DataTypes.TEXT }, // JSON
        newValues: { type: DataTypes.TEXT }, // JSON
        description: { type: DataTypes.STRING },
        ipAddress: { type: DataTypes.STRING },
        userAgent: { type: DataTypes.STRING }
    }, {
        tableName: 'audit_logs',
        indexes: [
            { fields: ['tableName', 'recordId'] },
            { fields: ['userId'] },
            { fields: ['timestamp'] },
            { fields: ['action'] }
        ],
        // Prevent updates and deletes on audit log
        hooks: {
            beforeUpdate: () => { throw new Error('Audit logs are immutable and cannot be updated'); },
            beforeDestroy: () => { throw new Error('Audit logs are immutable and cannot be deleted'); }
        }
    });

    // ============================================
    // DOCUMENT ATTACHMENTS (for mandatory attachment support)
    // ============================================

    const DocumentAttachment = sequelize.define('DocumentAttachment', {
        id: { type: DataTypes.STRING, primaryKey: true },
        documentType: { type: DataTypes.STRING, allowNull: false }, // 'Invoice', 'Bill', 'Payment', 'JournalEntry', etc.
        documentId: { type: DataTypes.STRING, allowNull: false },
        fileName: { type: DataTypes.STRING, allowNull: false },
        fileSize: { type: DataTypes.INTEGER },
        mimeType: { type: DataTypes.STRING },
        filePath: { type: DataTypes.STRING }, // Storage path or URL
        uploadedBy: { type: DataTypes.STRING },
        uploadedAt: { type: DataTypes.STRING }
    }, {
        tableName: 'document_attachments',
        indexes: [{ fields: ['documentType', 'documentId'] }]
    });

    // ============================================
    // SEQUENCE COUNTERS (for document numbering)
    // ============================================

    const SequenceCounter = sequelize.define('SequenceCounter', {
        id: { type: DataTypes.STRING, primaryKey: true },
        prefix: { type: DataTypes.STRING, allowNull: false, unique: true }, // 'JE', 'INV', 'BILL', 'PMT', etc.
        currentValue: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
        paddingLength: { type: DataTypes.INTEGER, defaultValue: 5 }, // JE-00001
        fiscalYearId: { type: DataTypes.STRING }
    }, { tableName: 'sequence_counters' });

    // ============================================
    // RELATIONSHIPS
    // ============================================

    // Fiscal Years & Periods
    FiscalYear.hasMany(AccountingPeriod, { foreignKey: 'fiscalYearId', as: 'periods' });
    AccountingPeriod.belongsTo(FiscalYear, { foreignKey: 'fiscalYearId' });

    // Journal Entry Lines
    JournalEntry.hasMany(JournalEntryLine, { foreignKey: 'journalEntryId', as: 'lines' });
    JournalEntryLine.belongsTo(JournalEntry, { foreignKey: 'journalEntryId' });

    // JE reversal self-reference
    JournalEntry.belongsTo(JournalEntry, { foreignKey: 'reversalOf', as: 'originalEntry' });
    JournalEntry.hasOne(JournalEntry, { foreignKey: 'reversedBy', as: 'reversalEntry' });

    // Cost Center hierarchy
    CostCenter.belongsTo(CostCenter, { foreignKey: 'parentId', as: 'parent' });
    CostCenter.hasMany(CostCenter, { foreignKey: 'parentId', as: 'children' });

    // Estimates
    Estimate.hasMany(EstimateItem, { foreignKey: 'estimateId', as: 'items' });
    EstimateItem.belongsTo(Estimate, { foreignKey: 'estimateId' });

    // Sales Orders
    SalesOrder.hasMany(SalesOrderItem, { foreignKey: 'salesOrderId', as: 'items' });
    SalesOrderItem.belongsTo(SalesOrder, { foreignKey: 'salesOrderId' });
    SalesOrder.belongsTo(Estimate, { foreignKey: 'estimateId', as: 'estimate' });

    // Credit Notes
    CreditNote.hasMany(CreditNoteItem, { foreignKey: 'creditNoteId', as: 'items' });
    CreditNoteItem.belongsTo(CreditNote, { foreignKey: 'creditNoteId' });

    // Bills
    Bill.hasMany(BillItem, { foreignKey: 'billId', as: 'items' });
    BillItem.belongsTo(Bill, { foreignKey: 'billId' });
    Bill.belongsTo(Vendor, { foreignKey: 'vendorId' });
    Vendor.hasMany(Bill, { foreignKey: 'vendorId', as: 'bills' });

    // Vendor Credits
    VendorCredit.hasMany(VendorCreditItem, { foreignKey: 'vendorCreditId', as: 'items' });
    VendorCreditItem.belongsTo(VendorCredit, { foreignKey: 'vendorCreditId' });
    VendorCredit.belongsTo(Vendor, { foreignKey: 'vendorId' });

    // Payments & Allocations
    Payment.hasMany(PaymentAllocation, { foreignKey: 'paymentId', as: 'allocations' });
    PaymentAllocation.belongsTo(Payment, { foreignKey: 'paymentId' });

    // Tax
    TaxGroup.hasMany(TaxGroupTax, { foreignKey: 'taxGroupId', as: 'taxes' });
    TaxGroupTax.belongsTo(TaxGroup, { foreignKey: 'taxGroupId' });
    TaxCode.hasMany(TaxGroupTax, { foreignKey: 'taxCodeId' });
    TaxGroupTax.belongsTo(TaxCode, { foreignKey: 'taxCodeId' });

    // Banking
    BankAccount.hasMany(BankStatement, { foreignKey: 'bankAccountId', as: 'statements' });
    BankStatement.belongsTo(BankAccount, { foreignKey: 'bankAccountId' });
    BankAccount.hasMany(BankTransaction, { foreignKey: 'bankAccountId', as: 'transactions' });
    BankTransaction.belongsTo(BankAccount, { foreignKey: 'bankAccountId' });
    BankStatement.hasMany(BankTransaction, { foreignKey: 'statementId', as: 'transactions' });

    // Budgets
    Budget.hasMany(BudgetLine, { foreignKey: 'budgetId', as: 'lines' });
    BudgetLine.belongsTo(Budget, { foreignKey: 'budgetId' });

    return {
        FiscalYear,
        AccountingPeriod,
        JournalEntry,
        JournalEntryLine,
        CostCenter,
        Project,
        Vendor,
        Estimate,
        EstimateItem,
        SalesOrder,
        SalesOrderItem,
        CreditNote,
        CreditNoteItem,
        Bill,
        BillItem,
        VendorCredit,
        VendorCreditItem,
        Payment,
        PaymentAllocation,
        TaxGroup,
        TaxCode,
        TaxGroupTax,
        BankAccount,
        BankStatement,
        BankTransaction,
        Budget,
        BudgetLine,
        AuditLog,
        DocumentAttachment,
        SequenceCounter
    };
}
